import { getStoredCustomScenarios } from './storage';

export type ScenarioCategory = 'clicking' | 'tracking' | 'switching' | 'precision';

export interface PlayerPosition {
  x: number;
  y: number;
  z: number;
}

export interface ScenarioDef {
  id: string;
  name: string;
  category: ScenarioCategory;
  description: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced' | 'Pro';
  durationSeconds: number;
  targetCount: number;
  targetRadius: number;
  targetSpeed: number;
  arenaType: '1-wall' | '6-wall' | 'open-arena';
  playerPosition: PlayerPosition;
  hasLifetimeLimit?: boolean;
  lifetimeMs?: number;
  pathType?: 'linear' | 'sinusoidal' | 'erratic' | 'lissajous' | 'airstrafe';
  spawnConstraint?: 'horizontal-line';
  escalationMode?: 'shrinking-radius' | 'speed-ramp';
  directionChangeIntervalMs?: number;
  speedVariance?: number;
  enableJukes?: boolean;
  maxHp?: number;
  damagePerHit?: number;
  fireMode?: 'semi' | 'auto';
  tags: string[];
  recommendedCm360: string;
  iconName: string;
  isCustom?: boolean;
}

export interface WarmupRoutine {
  id: string;
  name: string;
  description: string;
  drillIds: string[];
  isBuiltIn?: boolean;
}

export const SCENARIOS: ScenarioDef[] = [
  {
    id: 'gridshot-classic',
    name: 'GRIDSHOT // CLASSIC',
    category: 'clicking',
    description: '3 static targets on a front wall. Click 1, it instantly respawns in a new location. Pure speed & spatial rhythm.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.45,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 1.8 },
    tags: ['FLICKING', 'SPEED', 'SPATIAL'],
    recommendedCm360: '25-35 cm',
    iconName: 'Grid',
  },
  {
    id: 'flickshot-pro',
    name: 'FLICKSHOT // PRO',
    category: 'clicking',
    description: 'Targets spawn across wide angular spans and varying depths. Sharp flick resets and crosshair re-centering.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.4,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.8 },
    tags: ['WIDE FLICK', 'RE-CENTERING', 'ANGULAR'],
    recommendedCm360: '20-30 cm',
    iconName: 'Zap',
  },
  {
    id: 'tracking-sphere',
    name: 'SPHERE // TRACKING',
    category: 'tracking',
    description: 'Continuous target floating along smooth sinusoidal trajectories. Multi-hit target requiring 3 damage points.',
    difficulty: 'Beginner',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.55,
    targetSpeed: 2.3,
    maxHp: 3,
    damagePerHit: 1,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.5 },
    pathType: 'sinusoidal',
    directionChangeIntervalMs: 1200,
    speedVariance: 0.35,
    tags: ['SMOOTHNESS', 'CONTINUOUS', 'SINUSOIDAL', 'MULTI-HIT'],
    recommendedCm360: '30-45 cm',
    iconName: 'Move',
  },
  {
    id: 'micro-flicks',
    name: 'MICRO // PRECISION',
    category: 'precision',
    description: 'Compact sphere targets positioned close to center. Requires sub-pixel accuracy and minimal wrist strain.',
    difficulty: 'Pro',
    durationSeconds: 45,
    targetCount: 3,
    targetRadius: 0.25,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 4.8 },
    tags: ['MICRO', 'HEADSHOT', 'SUB-PIXEL'],
    recommendedCm360: '35-50 cm',
    iconName: 'Target',
  },
  {
    id: 'smoothswitch-heavy',
    name: 'SMOOTHSWITCH // HEAVY TARGETS',
    category: 'switching',
    description: '3 high-health moving targets requiring sustained full-auto fire to destroy. Train smooth target switching and recoil control.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.45,
    targetSpeed: 1.8,
    maxHp: 3,
    damagePerHit: 1,
    fireMode: 'auto',
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.5 },
    pathType: 'linear',
    tags: ['SMOOTHSWITCH', 'MULTI-HIT', 'AUTO-FIRE', 'SPRAY TRANSFER'],
    recommendedCm360: '25-35 cm',
    iconName: 'Zap',
  },
  {
    id: 'spray-control',
    name: 'SPRAY CONTROL // MULTI-HIT DUMMIES',
    category: 'clicking',
    description: '4 static dummy targets with 4 HP each. Hold down full-auto fire to track recoil and land continuous multi-bullet bursts.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.42,
    targetSpeed: 0,
    maxHp: 4,
    damagePerHit: 1,
    fireMode: 'auto',
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.0 },
    tags: ['SPRAY CONTROL', 'BURST', 'AUTO-FIRE', 'MULTI-HP'],
    recommendedCm360: '20-30 cm',
    iconName: 'Sliders',
  },
  {
    id: 'reflex-reactivation',
    name: 'REFLEX // 650MS',
    category: 'switching',
    description: 'Targets expire after 650ms. High-intensity speed test enforcing instant reaction and decision making.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 2,
    targetRadius: 0.35,
    targetSpeed: 0,
    hasLifetimeLimit: true,
    lifetimeMs: 650,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.5 },
    tags: ['REFLEX', 'REACTION', 'SPEED', 'EXPIRE'],
    recommendedCm360: '20-30 cm',
    iconName: 'Clock',
  },
  {
    id: 'strafe-tracking',
    name: 'STRAFE // HORIZONTAL',
    category: 'tracking',
    description: 'Target executes horizontal strafe patterns with sudden direction reversals. Isolates horizontal wrist tracking.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.42,
    targetSpeed: 3.2,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.0 },
    pathType: 'erratic',
    directionChangeIntervalMs: 800,
    speedVariance: 0.25,
    enableJukes: true,
    tags: ['STRAFE', 'HORIZONTAL', 'JUKES'],
    recommendedCm360: '30-40 cm',
    iconName: 'Move',
  },
  {
    id: 'six-wall-broad',
    name: '6-WALL // 360 DEGREE',
    category: 'clicking',
    description: 'Targets spawn all around you across 4 walls (front, back, left, right). Requires full 360-degree spatial awareness.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 5,
    targetRadius: 0.45,
    targetSpeed: 0,
    arenaType: '6-wall',
    playerPosition: { x: 0, y: 2.2, z: 0 },
    tags: ['360 DEGREE', 'SPATIAL AWARENESS', '6-WALL'],
    recommendedCm360: '20-30 cm',
    iconName: 'Compass',
  },
  {
    id: 'gridshot-small-grid',
    name: 'GRIDSHOT // DENSE CLUSTER',
    category: 'clicking',
    description: 'Densely packed small targets in a tight central cluster. Rapid micro-flicking with high accuracy demands.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.28,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.5 },
    tags: ['DENSE CLUSTER', 'MICRO-FLICK', 'ACCURACY'],
    recommendedCm360: '25-35 cm',
    iconName: 'Grid',
  },
  {
    id: 'burst-timing-click',
    name: 'BURST // TIMING CLICK',
    category: 'clicking',
    description: 'Pairs of short-lived targets (650ms window) with a 150ms visual pre-spawn warm pulse indicator. Train rhythm and trained reflex timing.',
    difficulty: 'Pro',
    durationSeconds: 45,
    targetCount: 2,
    targetRadius: 0.32,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.5 },
    hasLifetimeLimit: true,
    lifetimeMs: 650,
    tags: ['BURST', 'HIGH FREQUENCY', 'FLICK PAIR', 'TELEGRAPHED'],
    recommendedCm360: '20-30 cm',
    iconName: 'Zap',
  },
  {
    id: 'airstrafe-tracking',
    name: 'AIRSTRAFE // 3D TRACKING',
    category: 'tracking',
    description: 'Target executes high-verticality air-strafes and 3D parabolic arcs. Simulates movement shooters (Apex, Overwatch).',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.48,
    targetSpeed: 3.6,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.8 },
    pathType: 'airstrafe',
    directionChangeIntervalMs: 500,
    speedVariance: 0.6,
    enableJukes: true,
    tags: ['AIR STRAFE', 'VERTICALITY', 'PRO TRACKING'],
    recommendedCm360: '25-35 cm',
    iconName: 'Move',
  },
  {
    id: 'multi-target-switching',
    name: 'MULTI-TARGET // SWITCHING',
    category: 'switching',
    description: '6 static targets active simultaneously. Eliminating 1 instantly spawns another. Tests target-switching rhythm and multi-kill speed.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 6,
    targetRadius: 0.42,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.2 },
    tags: ['SWITCHING', 'KOVAAKS STYLE', 'MULTI-TARGET'],
    recommendedCm360: '25-35 cm',
    iconName: 'Zap',
  },
  {
    id: 'long-range-sniper',
    name: 'LONG RANGE // PRECISION',
    category: 'precision',
    description: 'Micro-sized targets (0.18 radius) at extended distance. Train sniper first-bullet accuracy & pixel clicks from far back.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.18,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 4.8 },
    tags: ['SNIPER', 'EXTENDED DISTANCE', 'LONG RANGE', 'PIXEL'],
    recommendedCm360: '35-55 cm',
    iconName: 'Target',
  },
  {
    id: 'escalating-precision',
    name: 'ESCALATING // PRECISION',
    category: 'precision',
    description: 'Target radius dynamically shrinks from 0.40 down to 0.18 as the session progresses. Test precision under escalating pressure.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.40,
    targetSpeed: 0,
    escalationMode: 'shrinking-radius',
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.5 },
    tags: ['ESCALATING', 'SHRINKING', 'DYNAMIC DIFFICULTY', 'PRECISION'],
    recommendedCm360: '30-50 cm',
    iconName: 'Target',
  },
  {
    id: 'accuracy-gauntlet-timed',
    name: 'ACCURACY GAUNTLET // 95% REQ',
    category: 'precision',
    description: 'Strict precision drill. Targets spawn at random depths with zero speed margin — miss penalties severely degrade final score.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.32,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.0 },
    tags: ['GAUNTLET', 'ACCURACY CRITICAL', 'PENALTY'],
    recommendedCm360: '30-45 cm',
    iconName: 'Crosshair',
  },
  {
    id: 'gridshot-wide-grid',
    name: 'GRIDSHOT // WIDE SPAN',
    category: 'clicking',
    description: '3 static targets on a wider horizontal grid. Demands large arm flicks combined with fine wrist adjustments.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.48,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 1.5 },
    tags: ['WIDE SPAN', 'ARM FLICK', 'GRIDSHOT'],
    recommendedCm360: '20-30 cm',
    iconName: 'Grid',
  },
  {
    id: 'chaos-switch',
    name: 'CHAOS // HIGH-TEMPO SWITCH',
    category: 'switching',
    description: '4 fast-respawning targets with a 580ms expiry limit. Rebalanced Pro-level drill testing rapid target prioritization.',
    difficulty: 'Pro',
    durationSeconds: 45,
    targetCount: 4,
    targetRadius: 0.35,
    targetSpeed: 0,
    hasLifetimeLimit: true,
    lifetimeMs: 580,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.5 },
    tags: ['CHAOS', 'HIGH TEMPO', 'PRO DRILL', 'EXPIRE'],
    recommendedCm360: '20-30 cm',
    iconName: 'Zap',
  },
  {
    id: 'figure8-tracking',
    name: 'FIGURE-8 // SMOOTH TRACKING',
    category: 'tracking',
    description: 'Target follows a true 2-axis Lissajous figure-8 curve. Train dual-axis diagonal smoothness.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.45,
    targetSpeed: 2.8,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.2 },
    pathType: 'lissajous',
    directionChangeIntervalMs: 1500,
    speedVariance: 0.2,
    tags: ['FIGURE-8', 'LISSAJOUS', 'DUAL AXIS', 'SMOOTHNESS'],
    recommendedCm360: '30-45 cm',
    iconName: 'Move',
  },
  {
    id: 'multitarget-tracking',
    name: 'DUAL // MULTI-TRACKING',
    category: 'tracking',
    description: '2 independent moving targets simultaneously. Divide tracking focus and switch between active targets smoothly.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 2,
    targetRadius: 0.4,
    targetSpeed: 2.6,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.2 },
    pathType: 'erratic',
    directionChangeIntervalMs: 900,
    speedVariance: 0.3,
    enableJukes: true,
    tags: ['DUAL TRACKING', 'MULTI-TARGET', 'PRO TRACKING'],
    recommendedCm360: '25-35 cm',
    iconName: 'Move',
  },
  {
    id: 'reflex-chain-endurance',
    name: 'REFLEX CHAIN // ENDURANCE',
    category: 'clicking',
    description: '90-second endurance drill with short-lived targets. Tests mental focus and consistent flicking output over time.',
    difficulty: 'Advanced',
    durationSeconds: 90,
    targetCount: 3,
    targetRadius: 0.38,
    targetSpeed: 0,
    hasLifetimeLimit: true,
    lifetimeMs: 800,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.4 },
    tags: ['ENDURANCE', 'STAMINA', 'REFLEX CHAIN'],
    recommendedCm360: '22-32 cm',
    iconName: 'Clock',
  },
  {
    id: 'headshot-line',
    name: 'HEADSHOT // HORIZONTAL LINE',
    category: 'precision',
    description: 'Targets spawn strictly constrained along an eye-level horizontal line (Y = 2.2). Isolates purely horizontal crosshair placement.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.35,
    targetSpeed: 0,
    spawnConstraint: 'horizontal-line',
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.0 },
    tags: ['HEADSHOT LINE', 'HORIZONTAL CROSSHAIR', 'PLACEMENT'],
    recommendedCm360: '30-45 cm',
    iconName: 'Target',
  },
];

export const PRESET_ROUTINES: WarmupRoutine[] = [
  {
    id: 'routine-5min-general',
    name: '5-MINUTE GENERAL WARMUP',
    description: 'Balanced warmup chaining flicking, precision, and tracking before competitive play.',
    drillIds: ['gridshot-classic', 'flickshot-pro', 'tracking-sphere'],
    isBuiltIn: true,
  },
  {
    id: 'routine-reflex-timing',
    name: 'REFLEX & TIMING INTENSIVE',
    description: 'High-tempo reflex activation drill sequence for clutch timing under pressure.',
    drillIds: ['burst-timing-click', 'reflex-reactivation', 'accuracy-gauntlet-timed'],
    isBuiltIn: true,
  },
  {
    id: 'routine-pure-precision',
    name: 'PURE PRECISION & CONTROL',
    description: 'Micro-flicking and long-range pixel precision for tactical shooter headshots.',
    drillIds: ['micro-flicks', 'gridshot-small-grid', 'long-range-sniper'],
    isBuiltIn: true,
  },
];

export const BENCHMARK_SEQUENCE_IDS = [
  'gridshot-classic',
  'strafe-tracking',
  'micro-flicks',
  'multi-target-switching',
];

export function getAllScenarios(): ScenarioDef[] {
  const custom = getStoredCustomScenarios();
  return [...SCENARIOS, ...custom];
}

export function getScenarioById(id: string): ScenarioDef {
  const all = getAllScenarios();
  return all.find((s) => s.id === id) || SCENARIOS[0];
}
