import { getStoredCustomScenarios } from './storage';

export type ScenarioCategory = 'clicking' | 'tracking' | 'switching' | 'precision';

export interface PlayerPosition {
  x: number;
  y: number;
  z: number;
}

export interface ScenarioDef {
  id: string;
  name: string;
  category: ScenarioCategory;
  description: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced' | 'Pro';
  durationSeconds: number;
  targetCount: number;
  targetRadius: number;
  targetSpeed: number;
  arenaType: '1-wall' | '6-wall' | 'open-arena';
  playerPosition: PlayerPosition;
  hasLifetimeLimit?: boolean;
  lifetimeMs?: number;
  pathType?: 'linear' | 'sinusoidal' | 'erratic';
  directionChangeIntervalMs?: number;
  speedVariance?: number;
  enableJukes?: boolean;
  maxHp?: number;
  damagePerHit?: number;
  fireMode?: 'semi' | 'auto';
  tags: string[];
  recommendedCm360: string;
  iconName: string;
  isCustom?: boolean;
}

export interface WarmupRoutine {
  id: string;
  name: string;
  description: string;
  drillIds: string[];
  isBuiltIn?: boolean;
}

export const SCENARIOS: ScenarioDef[] = [
  {
    id: 'gridshot-classic',
    name: 'GRIDSHOT // CLASSIC',
    category: 'clicking',
    description: '3 static targets on a front wall. Click 1, it instantly respawns in a new location. Pure speed & spatial rhythm.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.45,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 1.8 },
    tags: ['FLICKING', 'SPEED', 'SPATIAL'],
    recommendedCm360: '25-35 cm',
    iconName: 'Grid',
  },
  {
    id: 'flickshot-pro',
    name: 'FLICKSHOT // PRO',
    category: 'clicking',
    description: 'Targets spawn across wide angular spans and varying depths. Sharp flick resets and crosshair re-centering.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.4,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.8 },
    tags: ['WIDE FLICK', 'RE-CENTERING', 'ANGULAR'],
    recommendedCm360: '20-30 cm',
    iconName: 'Zap',
  },
  {
    id: 'tracking-sphere',
    name: 'SPHERE // TRACKING',
    category: 'tracking',
    description: 'Continuous target floating along dynamic Lissajous & sinusoidal trajectories. Multi-hit target requiring 3 damage points.',
    difficulty: 'Beginner',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.55,
    targetSpeed: 2.3,
    maxHp: 3,
    damagePerHit: 1,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.5 },
    pathType: 'sinusoidal',
    directionChangeIntervalMs: 1200,
    speedVariance: 0.35,
    tags: ['SMOOTHNESS', 'CONTINUOUS', 'SINUSOIDAL', 'MULTI-HIT'],
    recommendedCm360: '30-45 cm',
    iconName: 'Move',
  },
  {
    id: 'micro-flicks',
    name: 'MICRO // PRECISION',
    category: 'precision',
    description: 'Compact sphere targets positioned close to center. Requires sub-pixel accuracy and minimal wrist strain.',
    difficulty: 'Pro',
    durationSeconds: 45,
    targetCount: 3,
    targetRadius: 0.25,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 4.8 },
    tags: ['MICRO', 'HEADSHOT', 'SUB-PIXEL'],
    recommendedCm360: '35-50 cm',
    iconName: 'Target',
  },
  {
    id: 'pinpoint-micro',
    name: 'PINPOINT // ULTRA PRECISION',
    category: 'precision',
    description: 'Ultra-small targets (0.16 radius) at extended range. No speed pressure — pure focus on first-bullet sub-pixel placement.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.25,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 4.8 },
    tags: ['SNIPER', 'EXTENDED DISTANCE', 'LONG RANGE', 'PIXEL'],
    recommendedCm360: '35-55 cm',
    iconName: 'Target',
  },
  {
    id: 'smoothswitch-heavy',
    name: 'SMOOTHSWITCH // HEAVY TARGETS',
    category: 'switching',
    description: '3 high-health sphere targets requiring sustained auto-fire to destroy. Train smooth target-switching & spray transfer.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.45,
    targetSpeed: 0,
    maxHp: 3,
    damagePerHit: 1,
    fireMode: 'auto',
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.5 },
    tags: ['SMOOTHSWITCH', 'MULTI-HIT', 'AUTO-FIRE', 'SPRAY TRANSFER'],
    recommendedCm360: '25-35 cm',
    iconName: 'Zap',
  },
  {
    id: 'spray-control',
    name: 'SPRAY CONTROL // MULTI-HIT DUMMIES',
    category: 'clicking',
    description: '4 static dummy targets with 4 HP each. Hold down full-auto fire to track recoil and land continuous multi-bullet bursts.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.42,
    targetSpeed: 0,
    maxHp: 4,
    damagePerHit: 1,
    fireMode: 'auto',
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.0 },
    tags: ['SPRAY CONTROL', 'BURST', 'AUTO-FIRE', 'MULTI-HP'],
    recommendedCm360: '20-30 cm',
    iconName: 'Sliders',
  },
  {
    id: 'switching-gauntlet',
    name: 'SWITCHING // MIXED HP GAUNTLET',
    category: 'switching',
    description: '5 targets spawning across wide wall angles with 2 HP each. Rapid auto-fire switching gauntlet for reflex control.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 5,
    targetRadius: 0.38,
    targetSpeed: 0,
    maxHp: 2,
    damagePerHit: 1,
    fireMode: 'auto',
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.2 },
    tags: ['GAUNTLET', 'REFLEX', 'AUTO-FIRE', 'SWITCHING'],
    recommendedCm360: '25-35 cm',
    iconName: 'Zap',
  },
  {
    id: 'reflex-reactivation',
    name: 'REFLEX // 650MS',
    category: 'switching',
    description: 'Single target with 650ms expiration window. Train immediate reflex activation.',
    difficulty: 'Advanced',
    durationSeconds: 45,
    targetCount: 1,
    targetRadius: 0.4,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.2 },
    hasLifetimeLimit: true,
    lifetimeMs: 650,
    tags: ['REACTION', 'TIMED WINDOW', 'REFLEX'],
    recommendedCm360: '25-35 cm',
    iconName: 'Clock',
  },
  {
    id: 'strafe-tracking',
    name: 'STRAFE // HORIZONTAL',
    category: 'tracking',
    description: 'Target moves along horizontal wall plane with rapid direction changes. Multi-hit target requiring 3 damage points.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.45,
    targetSpeed: 2.9,
    maxHp: 3,
    damagePerHit: 1,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.0 },
    pathType: 'erratic',
    directionChangeIntervalMs: 600,
    speedVariance: 0.5,
    enableJukes: true,
    tags: ['STRAFE', 'READING', 'JUKES', 'UNPREDICTABLE', 'MULTI-HIT'],
    recommendedCm360: '30-40 cm',
    iconName: 'Sliders',
  },
  {
    id: 'six-wall-broad',
    name: '360° // 6-WALL ARENA',
    category: 'clicking',
    description: 'Full 360-degree room layout. Targets spawn behind, above, and around the player. Tests spatial orientation & 180° turns.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 5,
    targetRadius: 0.45,
    targetSpeed: 0,
    arenaType: '6-wall',
    playerPosition: { x: 0, y: 2.2, z: 0.0 },
    tags: ['360 DEGREE', 'SPATIAL', 'ROOM'],
    recommendedCm360: '20-30 cm',
    iconName: 'Maximize',
  },
  {
    id: 'gridshot-small-grid',
    name: 'GRIDSHOT // SMALL GRID',
    category: 'precision',
    description: 'High-density small target grid (0.22 radius). Perfect for fine-motor control and elite clicking accuracy.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.22,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 4.2 },
    tags: ['ULTRA PRECISION', 'SMALL GRID', 'CLUTCH'],
    recommendedCm360: '35-50 cm',
    iconName: 'Grid',
  },
  {
    id: 'burst-timing-click',
    name: 'BURST // TIMING CLICK',
    category: 'switching',
    description: 'Single high-tempo target with 500ms window. Master rhythm and timing under pressure.',
    difficulty: 'Pro',
    durationSeconds: 45,
    targetCount: 1,
    targetRadius: 0.35,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.5 },
    hasLifetimeLimit: true,
    lifetimeMs: 500,
    tags: ['BURST', 'HIGH FREQUENCY', 'FLICK PAIR'],
    recommendedCm360: '20-30 cm',
    iconName: 'Zap',
  },
  {
    id: 'airstrafe-tracking',
    name: 'AIRSTRAFE // 3D TRACKING',
    category: 'tracking',
    description: 'Target executes high-verticality air-strafes and erratic 3D arcs. Simulates movement shooters (Apex, Overwatch, Hyperscape).',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.48,
    targetSpeed: 3.6,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.8 },
    pathType: 'erratic',
    directionChangeIntervalMs: 500,
    speedVariance: 0.6,
    enableJukes: true,
    tags: ['AIR STRAFE', 'VERTICALITY', 'PRO TRACKING'],
    recommendedCm360: '25-35 cm',
    iconName: 'Move',
  },
  {
    id: 'multi-target-switching',
    name: 'MULTI-TARGET // SWITCHING',
    category: 'switching',
    description: '6 static targets active simultaneously. Eliminating 1 instantly spawns another. Tests target-switching rhythm and multi-kill speed.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 6,
    targetRadius: 0.42,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.2 },
    tags: ['SWITCHING', 'KOVAAKS STYLE', 'MULTI-TARGET'],
    recommendedCm360: '25-35 cm',
    iconName: 'Zap',
  },
  {
    id: 'long-range-sniper',
    name: 'LONG RANGE // PRECISION',
    category: 'precision',
    description: 'Micro-sized targets (0.18 radius) at extended distance. Train sniper first-bullet accuracy & pixel clicks from far back.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.18,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 7.2 },
    tags: ['LONG RANGE', 'SNIPER', 'PIXEL CLICK'],
    recommendedCm360: '40-60 cm',
    iconName: 'Target',
  },
  {
    id: 'escalating-precision',
    name: 'ESCALATING // PRECISION',
    category: 'precision',
    description: 'Compact micro targets at high distance requiring continuous precision. Tests sub-pixel click placement under pressure.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.2,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 5.5 },
    tags: ['ESCALATING', 'SHRINKING', 'ACCURACY'],
    recommendedCm360: '35-50 cm',
    iconName: 'Target',
  },
  {
    id: 'accuracy-gauntlet-timed',
    name: 'ACCURACY // GAUNTLET',
    category: 'switching',
    description: 'Ultra-fast 450ms expiration window, one target at a time. Rewards pure reaction speed and clutch flicking.',
    difficulty: 'Pro',
    durationSeconds: 45,
    targetCount: 1,
    targetRadius: 0.38,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.6 },
    hasLifetimeLimit: true,
    lifetimeMs: 450,
    tags: ['GAUNTLET', 'ACCURACY', '450MS'],
    recommendedCm360: '20-30 cm',
    iconName: 'Clock',
  },
  {
    id: 'gridshot-wide-grid',
    name: 'GRIDSHOT // WIDE SPAN',
    category: 'clicking',
    description: '4 static targets distributed across wide horizontal & vertical angles. Trains wide-angle flicks and large crosshair resets.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.42,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.0 },
    tags: ['WIDE SPAN', 'LARGE FLICK', 'SPEED'],
    recommendedCm360: '20-30 cm',
    iconName: 'Grid',
  },
  {
    id: 'pinpoint-micro',
    name: 'PINPOINT // ULTRA PRECISION',
    category: 'precision',
    description: 'Ultra-small targets (0.16 radius) at extended range. No speed pressure — pure focus on first-bullet sub-pixel placement.',
    difficulty: 'Pro',
    durationSeconds: 60,
    targetCount: 2,
    targetRadius: 0.16,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 6.5 },
    tags: ['PINPOINT', 'SUB-PIXEL', 'SNIPER'],
    recommendedCm360: '40-60 cm',
    iconName: 'Target',
  },
  {
    id: 'chaos-switch',
    name: 'CHAOS // HIGH-TEMPO SWITCH',
    category: 'switching',
    description: '8 active targets simultaneously spawning & expiring on a 400ms window. High-density target switching for clutch multi-kills.',
    difficulty: 'Pro',
    durationSeconds: 45,
    targetCount: 8,
    targetRadius: 0.38,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 2.4 },
    hasLifetimeLimit: true,
    lifetimeMs: 400,
    tags: ['CHAOS', 'HIGH TEMPO', 'SWITCHING'],
    recommendedCm360: '20-30 cm',
    iconName: 'Zap',
  },
  {
    id: 'figure8-tracking',
    name: 'FIGURE-8 // SMOOTH TRACKING',
    category: 'tracking',
    description: 'Continuous target tracing complex Lissajous figure-8 3D loops. Builds smooth rotational tracking and velocity matching.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 1,
    targetRadius: 0.5,
    targetSpeed: 2.7,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.2 },
    pathType: 'sinusoidal',
    directionChangeIntervalMs: 800,
    speedVariance: 0.4,
    tags: ['FIGURE-8', 'SMOOTHNESS', 'LISSAJOUS'],
    recommendedCm360: '30-45 cm',
    iconName: 'Move',
  },
  {
    id: 'multitarget-tracking',
    name: 'DUAL // MULTI-TRACKING',
    category: 'tracking',
    description: '2 simultaneously moving targets with independent erratic trajectories. Practice dynamic target transfer and dual tracking.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 2,
    targetRadius: 0.48,
    targetSpeed: 3.1,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.5 },
    pathType: 'erratic',
    directionChangeIntervalMs: 700,
    speedVariance: 0.5,
    enableJukes: true,
    tags: ['DUAL TRACKING', 'TARGET TRANSFER', 'ERRATIC'],
    recommendedCm360: '25-40 cm',
    iconName: 'Sliders',
  },
  {
    id: 'reflex-chain-endurance',
    name: 'REFLEX // ENDURANCE CHAIN',
    category: 'switching',
    description: 'Extended 90-second endurance chain with 600ms lifetime target windows. Train sustained reaction consistency under fatigue.',
    difficulty: 'Advanced',
    durationSeconds: 90,
    targetCount: 1,
    targetRadius: 0.42,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.0 },
    hasLifetimeLimit: true,
    lifetimeMs: 600,
    tags: ['ENDURANCE', 'SUSTAINED', 'REFLEX'],
    recommendedCm360: '25-35 cm',
    iconName: 'Clock',
  },
  {
    id: 'headshot-line',
    name: 'HEADSHOT // HORIZONTAL LINE',
    category: 'precision',
    description: 'Small targets constrained strictly to eye-level horizontal line plane. Master crosshair placement and micro horizontal flicks.',
    difficulty: 'Intermediate',
    durationSeconds: 60,
    targetCount: 3,
    targetRadius: 0.22,
    targetSpeed: 0,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 4.0 },
    tags: ['HEADSHOT', 'HORIZONTAL', 'CROSSHAIR PLACEMENT'],
    recommendedCm360: '30-45 cm',
    iconName: 'Target',
  },
  {
    id: 'smoothswitch-heavy',
    name: 'SMOOTHSWITCH // HEAVY TARGETS',
    category: 'switching',
    description: '3-HP heavy targets requiring multiple hits to destroy. Practice sustained target switching and recoil control.',
    difficulty: 'Advanced',
    durationSeconds: 60,
    targetCount: 4,
    targetRadius: 0.38,
    targetSpeed: 2.2,
    maxHp: 3,
    damagePerHit: 1,
    arenaType: '1-wall',
    playerPosition: { x: 0, y: 2.2, z: 3.5 },
    pathType: 'linear',
    tags: ['SMOOTHSWITCH', 'MULTI-HIT', 'HEAVY'],
    recommendedCm360: '25-40 cm',
    iconName: 'Layers',
  },
];

export const PRESET_ROUTINES: WarmupRoutine[] = [
  {
    id: 'routine-5min-general',
    name: '5-MINUTE GENERAL WARMUP',
    description: 'Balanced warmup chaining flicking, precision, and tracking before competitive play.',
    drillIds: ['gridshot-classic', 'flickshot-pro', 'tracking-sphere'],
    isBuiltIn: true,
  },
  {
    id: 'routine-reflex-timing',
    name: 'REFLEX & TIMING INTENSIVE',
    description: 'High-tempo reflex activation drill sequence for clutch timing under pressure.',
    drillIds: ['burst-timing-click', 'reflex-reactivation', 'accuracy-gauntlet-timed'],
    isBuiltIn: true,
  },
  {
    id: 'routine-pure-precision',
    name: 'PURE PRECISION & CONTROL',
    description: 'Micro-flicking and long-range pixel precision for tactical shooter headshots.',
    drillIds: ['micro-flicks', 'gridshot-small-grid', 'long-range-sniper'],
    isBuiltIn: true,
  },
];

export const BENCHMARK_SEQUENCE_IDS = [
  'gridshot-classic',
  'strafe-tracking',
  'micro-flicks',
  'multi-target-switching',
];

export function getAllScenarios(): ScenarioDef[] {
  const custom = getStoredCustomScenarios();
  return [...SCENARIOS, ...custom];
}

export function getScenarioById(id: string): ScenarioDef {
  const all = getAllScenarios();
  return all.find((s) => s.id === id) || SCENARIOS[0];
}


